### ISSUE TITLE
FormService is not provided ?

### ISSUE THREAD

**Issue by alexdzh** [neroniaky/angular2-token#65] opened 2016-11-21 11:06 UTC
I tried quckstart and received this error:
metadata_resolver.js:499Uncaught Error: Can't resolve all parameters for A2tFormComponent: (?).
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:24402:19)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:24303:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:24078:28)
    at http://localhost:4200/main.bundle.js:24147:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:24140:44)
    at http://localhost:4200/main.bundle.js:24128:50
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:24115:44)
    at http://localhost:4200/main.bundle.js:24128:50CompileMetadataResolver.getDependenciesMetadata @ metadata_resolver.js:499CompileMetadataResolver.getTypeMetadata @ metadata_resolver.js:400CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:175(anonymous function) @ metadata_resolver.js:244CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:237(anonymous function) @ metadata_resolver.js:225CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212(anonymous function) @ metadata_resolver.js:225CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212RuntimeCompiler._compileComponents @ runtime_compiler.js:133RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:71RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:62PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.ts:12__webpack_require__ @ bootstrap 5760104…:52(anonymous function) @ zone.js:1426__webpack_require__ @ bootstrap 5760104…:52webpackJsonpCallback @ bootstrap 5760104…:23(anonymous function) @ main.bundle.js:1

**Comment by neroniaky** [comment] 2016-11-21 14:48
@alexdzh thanks for your report. I guess you are using angular-cli again. Gonna give it a try later and see if I can reproduce this error.

**Comment by adonespitogo** [comment] 2016-11-21 15:37
I'm getting the same error with angular-cli

**Comment by neroniaky** [comment] 2016-11-21 15:55
Found the issue. Angular-cli does not like my the order of my imports. Currently working on a problem with the routing.

**Comment by adonespitogo** [comment] 2016-11-21 16:20
@neroniaky Cool :+1:

**Comment by adonespitogo** [comment] 2016-11-22 08:28
@neroniaky anything we can help?

**Comment by neroniaky** [comment] 2016-11-22 08:30
@adonespitogo I gonna commit my changes to the imports. Didn't have to get the routing to work yet. Maybe you can give it a try too. Should be a quick fix.

**Comment by fender053** [comment] 2016-11-29 00:56
I have the same error with Angular-cli. Any updates here?

**Comment by neroniaky** [comment] 2016-11-29 12:34
@fender053 with v0.2.0-beta.4 you shouldn't get this exact error anymore. There is still a problem with the routing, but this on should be fixed.

**Comment by fender053** [comment] 2016-11-30 20:17
@neroniaky you are correct. I get the following routing error when attempting to sign in:
error_handler.js:53 Error: Uncaught (in promise): Error: Cannot match any routes: 'restricted'
    at resolvePromise (zone.js:429)
    at zone.js:406
    at ZoneDelegate.invoke (zone.js:203)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:202)
    at Zone.run (zone.js:96)
    at zone.js:462
    at ZoneDelegate.invokeTask (zone.js:236)
    at Object.onInvokeTask (ng_zone_impl.js:34)
    at ZoneDelegate.invokeTask (zone.js:235)

**Comment by neroniaky** [comment] 2017-02-01 07:53
Duplicate of #113

**Closed by neroniaky** 2017-02-01 07:53 UTC
Labels: angular-cli, bug
