### ISSUE TITLE
OAuth via Github external window does not close

### ISSUE THREAD

**Issue by alikhan-io** [neroniaky/angular2-token#52] opened 2016-10-24 18:09 UTC
When using the OAuth button both in my local app as well as the demo site on angular2-token.herokuapp.com once you get to the callback, the second tab does not close nor is anything seemingly sent back to the original window. Was there some recent change that broke this functionality?

**Comment by neroniaky** [comment] 2016-10-24 18:24
@alikhan-io thanks for opening this issue. I opened a issue myself at devise token auth [Link](https://github.com/lynndylanhurley/devise_token_auth/issues/749) because I can't get it to work. Didn't get answer yet. The other Demo for AngularJS and JQuery seem to be broken too.

**Comment by neroniaky** [comment] 2016-11-29 08:57
Duplicate of  #[4](https://github.com/neroniaky/angular2-token-example/issues/4)

**Closed by neroniaky** 2016-11-29 08:57 UTC
